apiVersion: apps/v1
kind: Deployment
metadata:
    name: vsc-pandoc
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vsc-pandoc
    template:
        metadata:
            labels:
                app: vsc-pandoc
        spec:
            containers:
              - name: vsc-pandoc
                image: hittjw/vsc-pandoc:latest
                imagePullPolicy: IfNotPresent
                volumeMounts:
                  - mountPath: /capsule
                    name: pvc-smb-capsule
