apiVersion: apps/v1
kind: Deployment
metadata:
    name: vsc-ubuntu
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vsc-ubuntu
    template:
        metadata:
            labels:
                app: vsc-ubuntu
        spec:
            nodeSelector:
                kubernetes.io/arch: amd64
            containers:
                - name: vsc-ubuntu
                  image: hittjw/vsc-ubuntu:latest
                  env:
                    - name: TZ
                      value: "America/New_York"
                  imagePullPolicy: IfNotPresent
                  resources:
                    requests:
                      cpu: "1"
                    limits:
                      cpu: "4"
                  volumeMounts:
                    - name: pv-home
                      mountPath: /home
                    - name: pv-workspace
                      mountPath: /workspace
            volumes:
                - name: pv-home
                  persistentVolumeClaim:
                    claimName: pv-home
                - name: pv-workspace
                  persistentVolumeClaim:
                    claimName: pv-workspace 
