apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-capsule
spec:
  capacity:
    storage: 100Gi 
  accessModes:
    - ReadWriteMany
  mountOptions:
    - guest
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - vers=1.0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-capsule
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 192.168.3.20/capsule##
    volumeAttributes:
      source: //192.168.3.20/Capsule
    # The 'nodeStageSecretRef' is omitted for guest access
