apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-multiarch
  labels:
    app: ubuntu-multiarch
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ubuntu-multiarch
  template:
    metadata:
      labels:
        app: ubuntu-multiarch
    spec:
      # Allow any architecture (amd64 or arm64)
      # Uncomment below if you want to *restrict*
      # nodeSelector:
      #   kubernetes.io/arch: arm64
      containers:
      - name: ubuntu-tools
        image: ubuntu:22.04
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
          - "-c"
          - |
            echo "Updating packages..."
            apt-get update -y
            apt-get install -y git python3 default-jdk make
            echo "Starting sleep loop to keep container running..."
            tail -f /dev/null
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"