apiVersion: v1
kind: Service
metadata:
  name: pihole-lb
  namespace: kube-public
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.7
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  externalTrafficPolicy: Cluster