apiVersion: v1
kind: Service
metadata:
  name: lb-pihole
  namespace: kube-public
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.7
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53