apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: false
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
          - name: TZ
            value: "America/New_York"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 53
          protocol: TCP
        - containerPort: 80
          hostPort: 30080 
          protocol: TCP
        - containerPort: 443
          hostPort: 30443
          protocol: TCP
        env:
        - name: TZ
          value: "America/New_York"
        - name: FTLCONF_webserver_api_password
          value: "mydQcYCd9rlG"
        - name: FTLCONF_dns_listeningMode
          value: "all"
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME", "SYS_NICE"]
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pv-pihole
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: pv-dnsmasq
