apiVersion: v1
kind: Service
metadata:
  name: lb-pihole
  namespace: kube-public
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.7
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 30053
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 30053
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30443
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080