apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dnsmasq
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv-dnsmasq
    server: 172.17.0.2
