apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pihole
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  hostPath:
    path: /mnt/pv-pihole
    type: DirectoryOrCreate
