apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pihole
spec:
  capacity:
    storage: 1Gi
  nfs:
    path: /pv-pihole
    server: 172.17.0.2
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - hard
    - nfsvers=4.1
  volumeMode: Filesystem
