apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-dnsmasq
  namespace: kube-public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-dnsmasq