apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/homepage-pv
    type: DirectoryOrCreate
