- Prospect:
  - LinkedIn:
      description: Homepage is awesome
      href: https://www.linkedin.com/feed/
  - Hunter: 
      href: https://hunter.io/
- Technology: 
  - Pi-Hole:
      description: Needs Load Balancing
      href: https://192.168.3.7:30443/admin/
      widget: 
        type: pihole
        url: https://192.168.3.7:30443
        version: 6
        key: mydQcYCd9rlG
      