apiVersion: v1
kind: Service
metadata:
  name: obsidian-vnc-service
spec:
  type: NodePort  # Or LoadBalancer if you're running in a cloud provider
  ports:
  - port: 5901
    targetPort: 5901
  selector:
    app: obsidian-vnc
