apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: kube-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          env:
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 11434
              protocol: TCP
          env:
            - name: OLLAMA_HOST
              value: 0.0.0.0
      restartPolicy: Always
